# Generated by Django 3.2.9 on 2021-11-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadratic', '0002_auto_20211126_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadratics',
            name='roots',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
