# Generated by Django 3.2.9 on 2021-11-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadratic', '0003_quadratics_roots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadratics',
            name='roots',
            field=models.TextField(default=''),
        ),
    ]
