# Generated by Django 3.2.9 on 2021-11-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadratic', '0004_alter_quadratics_roots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadratics',
            name='roots',
        ),
    ]
