# Generated by Django 3.2.9 on 2021-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=35, verbose_name='Введіть функцію')),
                ('a', models.IntegerField(verbose_name='а')),
                ('b', models.IntegerField(verbose_name='b')),
                ('eps', models.FloatField(verbose_name='Введіть точність')),
            ],
        ),
    ]
