# Generated by Django 3.2.9 on 2021-11-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtons',
            old_name='b',
            new_name='max_iter',
        ),
        migrations.RenameField(
            model_name='newtons',
            old_name='a',
            new_name='x0',
        ),
    ]
